Add minimum OCaml version to opam file
Irmin 1.3 no longer works on 4.05 for some reason:

    File "src/irmin/type.ml", line 1123, characters 21-24:
    Error: The type constructor t expects 2 argument(s),
           but is here applied to 1 argument(s)